### ISSUE TITLE
Align-item issue

### ISSUE THREAD

**Issue by Alisyad9** [fac22/microblogging_site-DASE#35]
In the dive class "box", the Align-items are set to flex-start..... would suggest putting it to Center or stretch, since currently all all elements are left aligned. 👍 

``` css
.box {
  margin-top: 20pt;
  padding: 15pt;
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  border: 3pt solid black;
  max-width: 80%;
  background-color: white;
}
```
